# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nn_classification_cpp <- function(train, test, classes) {
    .Call(`_KDcpp_nn_classification_cpp`, train, test, classes)
}

