# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Nearest Neighbor Classification
#'
#' Finds the closest neighbor for each point in the test matrix
#' and returns a vector of classifications
#'
#' @param train A numeric matrix of training points
#' @param test A numeric matrix of test points
#' @param classes A integer vector of training point classifications
#' @export
nn_classification_cpp <- function(train, test, classes) {
    .Call(`_KDcpp_nn_classification_cpp`, train, test, classes)
}

